---
# tasks file for nginx.install
- name: install nginx RedHat
  yum:
    name: nginx
    state: "{{ nginx_install_state }}"
  when: ansible_os_family == "RedHat"

- name: install nginx RedHat
  apt:
    name: nginx
    state: "{{ nginx_install_state }}"
  when: ansible_os_family == "Debian"

- name: run and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes 
  when: (nginx_install_state == installed) or (nginx_install_state == latest)
